### ISSUE TITLE
octopusdeploy_variable importer doesn't import scope

### ISSUE THREAD

**Issue by cdhunt** [OctopusDeployLabs/terraform-provider-octopusdeploy#123]
It appears scope is not imported with `octopusdeploy_variable`.

I have an existing variable. The JSON export looks like this.

```json
    {
      "Id": "0906031f-68ba-4a15-afaa-657c1564e07b",
      "Name": "worker_pool_name",
      "Value": "dev",
      "Description": null,
      "Scope": {
        "Environment": [
          "Environments-1"
        ]
      },
      "IsEditable": true,
      "Prompt": null,
      "Type": "String",
      "IsSensitive": false
    }
```

So, I have a terraform config that looks like this. I ran terraform import to bring in the existing state.

```hcl
resource "octopusdeploy_variable" "worker_pool_name_dev" {

  name       = "worker_pool_name"
  project_id = "Projects-3" 
  type       = "String"

  value = "dev"

  scope {
    environments = [octopusdeploy_environment.dev.id]
  }
}
```

Terraform treats the scope as all new and needing creation.

```bash
> terraform plan

  # octopusdeploy_variable.worker_pool_name_dev will be updated in-place
  ~ resource "octopusdeploy_variable" "worker_pool_name_dev" {
        id           = "0906031f-68ba-4a15-afaa-657c1564e07b"
      + is_sensitive = false
        name         = "worker_pool_name"
        project_id   = "Projects-3"
        type         = "String"
        value        = "dev"

      + scope {
          + actions      = []
          + channels     = []
          + environments = [
              + "Environments-1",
            ]
          + machines     = []
          + roles        = []
          + tenant_tags  = []
        }
    }
```

**Comment by musaabal-okaidi** [comment]
I've also noticed issues whereby terraform doesn't seem to be aware of changes that have been made vi the Octopus console to the variable scope. 

if I make changes to the variable name or value, terraform will pick-up these changes and plans to reconcile them.

Is there an ETA for when this will be fixed?

**Comment by jbristowe** [comment]
Thanks for your patience on this issue. I'm tackling this issue now and should have a fix today.

**Comment by musaabal-okaidi** [comment]
> Thanks for your patience on this issue. I'm tackling this issue now and should have a fix today.

Thank you very much.

**Comment by jbristowe** [comment]
Hey @cdhunt and @musaabal-okaidi! I've implemented a change that allows updated to the `scope` properties. This allows supports importing a `scope` through its associated variable. Please confirm.

**Comment by musaabal-okaidi** [comment]
> Hey @cdhunt and @musaabal-okaidi! I've implemented a change that allows updated to the `scope` properties. This allows supports importing a `scope` through its associated variable. Please confirm.

Hi @jbristowe 

Unfortunately I'm still having the same. If I define a variable with scope in terraform then apply, the variable will be created along with the scopes, and if I make any modification to the scope in the terraform definitions it will update them accordingly. 

However; the issue I'm having is that if I manually change the scope from the UI then run a terraform plan or apply it doesn't detect the changes that have been made to the scope via the UI and it says the infrastructure is up to date.

Let me know if you want me to share any code or logs if that's not clear.

N.B I did initialise my project with version `0.7.10` the provider.

**Comment by jbristowe** [comment]
I have committed fixes that resolve this import and resource management bug associated with variable scopes. Please download [release v0.7.12+](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/releases/tag/v0.7.12) to see if this resolves the issue.

**Comment by musaabal-okaidi** [comment]
> I have committed fixes that resolve this import and resource management bug associated with variable scopes. Please download [release v0.7.12+](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/releases/tag/v0.7.12) to see if this resolves the issue.

Thanks John. Unfortunately I'm not in a position to test this for a while, but I do plan to come back to this in the future.

**Comment by jbristowe** [comment]
A fix is coming in the next release. 👍

**Comment by johnsimons** [comment]
This has been fixed in later version
