### ISSUE TITLE
Apply Terraform Action Is Always Tainted

### ISSUE THREAD

**Issue by evan-cleary** [OctopusDeployLabs/terraform-provider-octopusdeploy#147]
**Describe the bug**
The apply terraform action appears to be hard coded to specific values during expansion, this causes the state of the action to always be tainted.
 
This is currently preventing us from updating our terraform provider version as we utilize both the apply and plan terraform step actions. (previously both implemented with a generic action and working wonderfully.) We are unable to utilize our existing implementation with the newest provider because it always detects changes.

**Steps to reproduce**
1. Create an apply_terraform_action step action with a primary package and a `managed_account` value of AWS
2. Apply to step
3. Run apply again, plan will show changes

**Expected behavior**

**Logs and other supporting information**
```hcl
 apply_terraform_action {
                id                                 = "a2406e57-7963-49f1-beb9-40edbdf82019"
              ~ managed_account                    = "None" -> "AWS"
                name                               = "Apply Project Plan"
              ~ properties                         = {
                  - "Octopus.Action.Package.DownloadOnTentacle"             = "Server" -> null
                  - "Octopus.Action.Package.FeedId"                         = "Feeds-1061" -> null
                  - "Octopus.Action.Package.PackageId"                      = "{REDACTED}" -> null
                  - "Octopus.Action.RunOnServer"                            = "false" -> null
                  - "Octopus.Action.Script.ScriptSource"                    = "Package" -> null
                  - "Octopus.Action.Terraform.AllowPluginDownloads"         = "True" -> null
                  - "Octopus.Action.Terraform.ManagedAccount"               = "None" -> null
                    # (6 unchanged elements hidden)
                }
}
```

**Screenshots**

**Environment and versions:**
- OS: OSx
- Octopus Server Version: 2020.5.8
- Terraform Version: 0.14.7
- Octopus Terraform Provider Version: 0.7.15

**Additional context**

**Comment by jbristowe** [comment]
Hey @evan-cleary! :wave: Thanks for submitting this issue.

I've looked into this underlying behaviour for this action. There are quite a few properties that are missing. I've implemented those and I'll be creating a new release to support them soon.

**Comment by jbristowe** [comment]
Update: I've released an update to the provider that added a lot of functionality to this action. There was a lot missing. Please let me know how it goes.

**Comment by evan-cleary** [comment]
@jbristowe Sorry for the delay, was switched onto a couple other things and just got back to this. Still seeing some of the properties being tainted on re-apply

apply_terraform_template_action {
                id                                 = "85466e94-09bf-4bea-bc1f-aa2312144fcc"
                name                               = "Apply Project Plan"
              ~ properties                         = {
                  - "Octopus.Action.Aws.Region"                             = "#{AWS_REGION}" -> null
                  - "Octopus.Action.AwsAccount.UseInstanceRole"             = "true" -> null
                  - "Octopus.Action.Package.DownloadOnTentacle"             = "False" -> null
                  - "Octopus.Action.Package.FeedId"                         = "Feeds-1071" -> null
                  - "Octopus.Action.Package.PackageId"                      = "DT-SFI-ProdEng/aws-octopus" -> null
                  - "Octopus.Action.RunOnServer"                            = "false" -> null
                  - "Octopus.Action.Script.ScriptSource"                    = "Package" -> null
                  - "Octopus.Action.Terraform.AllowPluginDownloads"         = "true" -> null
                  - "Octopus.Action.Terraform.ManagedAccount"               = "AWS" -> null
                    # (3 unchanged elements hidden)
                }
                # (11 unchanged attributes hidden)




                # (4 unchanged blocks hidden)
            }
        }
Let me spin up a GIST and send you an example code.

**Comment by jbristowe** [comment]
Thanks! I'll take a look at this today.

**Comment by jbristowe** [comment]
The `apply_terraform_template_action` schema has been changed; the `template` property is now an aggregate type. Example:

```
resource "octopusdeploy_deployment_process" "terraform" {
  project_id = local.project_id

  step {
    name = "Apply Project Plan"

    apply_terraform_template_action {
      name        = "Apply Project Plan"
      is_required = true

      advanced_options {
        allow_additional_plugin_downloads = true
        apply_parameters                  = "apply-parameters"
        init_parameters                   = "init-parameters"
        plugin_cache_directory            = "plugin-cache-directory"
        workspace                         = "workspace"
      }

      aws_account {
        region            = "aws-region"
        use_instance_role = true
      }

      primary_package {
        package_id           = local.package_id
        feed_id              = local.feed_id
        acquisition_location = "Server"
      }

      template {
        additional_variable_files       = "additional-variable-files"
        directory                       = "template-directory"
        run_automatic_file_substitution = false
        target_files                    = "target-files"
      }
    }
  }
}
```
