### ISSUE TITLE
Creating the same variable with a different scope doesn't receive an ID

### ISSUE THREAD

**Issue by SanderKnape** [OctopusDeployLabs/terraform-provider-octopusdeploy#797]
**Describe the bug**
When creating two variables with the same name on a project, and they both have a different scope, the variable that is created last doesn't get its ID stored in state. This results in warnings in subsequent plans/applies, and that variable can't be edited or removed.

**Steps to reproduce**
The following two variables both have the same name but a different scope.
```
resource "octopusdeploy_variable" "var1" {
  owner_id = var.project_id
  type     = "String"
  name     = "TestingFromTF"
  value    = "test1"

  scope {
    environments = [
      var.environment1
    ]
  }
}

resource "octopusdeploy_variable" "var2" {
  owner_id = var.project_id
  type     = "String"
  name     = "TestingFromTF"
  value    = "test2"

  scope {
    environments = [
      var.environment2
    ]
  }
}
```

When first var1 is applied, then var2, a `terraform state show 'octopusdeploy_variable.var2` will show that no ID is set on this second variable.

**Expected behavior**
The variable should have an ID.

**Errors**

When trying to remove the variable with no ID, the following errors is shown:

```
VariableService: invalid parameter, variableID

Error: unable to delete variable
```

**Environment and versions:**
- OS: OSX
- Octopus Server Version: v2024.4 (Build 4121)
- Terraform Version: 19.7
- Octopus Terraform Provider Version: 0.32.0

**Additional context**
This looks like a follow up from https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/785.

**Comment by peter-majeed** [comment]
In my testing, this broke between version `0.23.1` and `0.30.0`.

**Comment by mik-ky** [comment]
Upgrading Octopus Server to the latest version of v2024.4 should fix the issue.

**Comment by SanderKnape** [comment]
It still does not return an ID when two variables for different scopes have the same value.

**Comment by mik-ky** [comment]
> It still does not return an ID when two variables for different scopes have the same value.

I cannot replicate this behaviour again in the latest version of 2024.4. Is it still a problem after [removing from the variables with invalid state using the cli](https://developer.hashicorp.com/terraform/cli/commands/state/rm#usage), the resource definitions, and the variables in Octopus Deploy and re-creating them?

**Comment by SanderKnape** [comment]
We're on Octopus Cloud version `2025.1.1913`.

With the following Terraform:

```
resource "octopusdeploy_variable" "var1" {
  owner_id = "Projects-2441"
  type     = "String"
  name     = "TestingFromTF"
  value    = "test1"

  scope {
    environments = [
      "Environments-26"
    ]
  }
}

resource "octopusdeploy_variable" "var2" {
  owner_id = "Projects-2441"
  type     = "String"
  name     = "TestingFromTF"
  value    = "test1" # same value as above

  scope {
    environments = [
      "Environments-27" # different scope as above
    ]
  }
}
```

I see the following output:

```
octopusdeploy_variable.var2: Creating...
octopusdeploy_variable.var1: Creating...
octopusdeploy_variable.var2: Creation complete after 0s [id=9e223aff-a2c7-4615-a6f3-f344b82785f2]
octopusdeploy_variable.var1: Creation complete after 1s
```

Note that `var2` was created first in this case, and that there is no `id` for `var1` in the "Creation complete" output.

This is also visible when showing the state:

```
❯ tf state show 'octopusdeploy_variable.var1'
# octopusdeploy_variable.var1:
resource "octopusdeploy_variable" "var1" {
    description  = null
    id           = null
    is_editable  = true
    is_sensitive = false
    name         = "TestingFromTF"
    owner_id     = "Projects-2441"
    space_id     = null
    type         = "String"
    value        = "test1"

    scope {
        environments = [
            "Environments-26",
        ]
    }
}
```

Because there is no ID, subsequent actions fail:

```
❯ tf plan
octopusdeploy_variable.var1: Refreshing state...
octopusdeploy_variable.var2: Refreshing state... [id=9e223aff-a2c7-4615-a6f3-f344b82785f2]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
╷
│ Warning: Error loading variable, with variable Id []
│
│   with octopusdeploy_variable.var1,
│   on main.tf line 16, in resource "octopusdeploy_variable" "var1":
│   16: resource "octopusdeploy_variable" "var1" {
│
│ VariableService: invalid parameter, variableID
```

**Comment by mik-ky** [comment]
@SanderKnape Strange - I can't replicate this anymore on both Octopus Server 2024.4 and 2025.1.x against v0.32.0 and latest version of the provider(but was able to replicate this on a lower 2024.4.x a while back).
```
tf apply                                                                                                                                                      ✔ │ 13:07:03 

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # octopusdeploy_variable.var1 will be created
  + resource "octopusdeploy_variable" "var1" {
      + id           = (known after apply)
      + is_editable  = true
      + is_sensitive = false
      + name         = "TestingFromTF1"
      + owner_id     = "Projects-2462"
      + space_id     = "Spaces-83"
      + type         = "String"
      + value        = "test1"
        # (1 unchanged attribute hidden)

      + scope {
          + environments = [
              + "Environments-202",
            ]
        }
    }

  # octopusdeploy_variable.var2 will be created
  + resource "octopusdeploy_variable" "var2" {
      + id           = (known after apply)
      + is_editable  = true
      + is_sensitive = false
      + name         = "TestingFromTF1"
      + owner_id     = "Projects-2462"
      + space_id     = "Spaces-83"
      + type         = "String"
      + value        = "test2"
        # (1 unchanged attribute hidden)

      + scope {
          + environments = [
              + "Environments-201",
            ]
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

octopusdeploy_variable.var1: Creating...
octopusdeploy_variable.var2: Creating...
octopusdeploy_variable.var2: Creation complete after 0s [id=f12a7594-2779-4307-898f-4bc539dd5322]
octopusdeploy_variable.var1: Creation complete after 1s [id=5547789f-f138-4924-84e2-312cc3a737a9]
```

**Comment by SanderKnape** [comment]
You're setting a different value on the second variable. This only happens when both variables have the same value.

**Comment by mik-ky** [comment]
> You're setting a different value on the second variable. This only happens when both variables have the same value.
> 
> Also please note that this works in version `0.23.1` of the Octopus provider.

You're right. Sorry, I must've modified the value accidentally and missed it when I came back to have a look at this again

**Comment by domenicsim1** [comment]
Hi @SanderKnape,
Thank you for your patience and information you have provided as we worked on this issue.
The fixed has been release in v0.37.2 of the provider. Please note this will not fix existing resources with missing IDs. Missing IDs will need to be manually restored in state or you will need to manually remove the variable from state and Octopus Server then recreated them.

**Comment by SanderKnape** [comment]
Thank you!
